let effectNames = [
	"n/a",
	"ugh",
	"exclamation point",
	"light bulb left",
	"haha",
	"three white lines left",
	"grrr",
	"three red lines",
	"question mark left",
	"thinking",
	"heart left",
	"dizzy",
	"wha left/right",
	"ellipses left",
	"three white lines right",
	"question mark right",
	"crying",
	"wha in/out",
	"firework middle",
	"firework left",
	"firework midleft",
	"heart right",
	"ellipses right",
	"light bulb right"
]
