let effectNames: [Int32: String] = [
	1: "ugh",
	2: "exclamation point",
	3: "light bulb left",
	4: "haha",
	5: "three white lines left",
	6: "grrr",
	7: "three red lines",
	8: "question mark left",
	9: "thinking",
	10: "heart left",
	11: "dizzy",
	12: "wha left/right",
	13: "ellipses left",
	14: "three white lines right",
	15: "question mark right",
	16: "crying",
	17: "wha in/out",
	18: "firework middle",
	19: "firework left",
	20: "firework midleft",
	21: "heart right",
	22: "ellipses right",
	23: "light bulb right"
]
