let mapNames: [Int32: String] = [
	4:   "Harbor Area Beta",
	5:   "Stadium Area Beta",
	6:   "Fighter Area Beta",
	7:   "Junk Depot",
	8:   "Cleaning Room",
	9:   "Fossil Guild",
	10:  "Diggins's Room",
	11:  "Fossil Center Lobby",
	12:  "Fossil Center Side Room 2",
	13:  "Richmond Building",
	14:  "Rosie's Room",
	15:  "Richmond's Office",
	16:  "Hallway To Secret Lab",
	17:  "Secret Lab",
	18:  "Fossil Center Left Hallway",
	19:  "Fossil Center Warehouse (Empty)",
	20:  "Hotel Room Right-2",
	21:  "Nick Nack's Room",
	22:  "Hotel Lobby",
	23:  "Hotel Room Right-3",
	24:  "Hotel Right Hallway",
	25:  "Hotel Left Hallway",
	26:  "Fossil Stadium Training Room",
	27:  "Fossil Stadium Lobby",
	28:  "Fossil Stadium Basement",
	29:  "Fossil Stadium Pre-Battle Room",
	30:  "Captain's Office",
	31:  "Police Station",
	32:  "Prison",
	33:  "Greenhorn Plains",
	34:  "Knotwood Forest Beta",
	35:  "Unused Knotwood Forest Area",
	36:  "Digadigamid 1F",
	37:  "Digadigamid 1F Keymonite Room",
	38:  "Digadigamid 2F",
	39:  "Digadigamid 3F",
	40:  "Digadigamid 4F",
	41:  "Unused Digadigamid Area",
	42:  "Rivet Ravine",
	43:  "Tunnel #1",
	44:  "Tunnel #2",
	45:  "Tunnel #3",
	46:  "Tunnel #4",
	47:  "Tunnel #5",
	48:  "Tunnel Entrance",
	49:  "Parchment Desert",
	50:  "Bottomsup Bay",
	51:  "Woolbeard's Room",
	52:  "Bottomsup Bay Left Hole", // ship
	53:  "Bottomsup Bay Middle Hole", // uhh
	54:  "Bottomsup Bay Right Hole", // uh
	55:  "Pirate Ship 1F",
	56:  "Pirate Ship 2F",
	57:  "Pirate Ship 3F",
	58:  "Pirate Ship 1F Chest Room",
	59:  "Pirate Ship 1F Misc Room",
	60:  "BB Base 1F",
	61:  "BB Base 2F",
	62:  "BB Base 6F",
	63:  "Coldfeet Glacier",
	64:  "Mt. Lavaflow (Lava Raised)",
	65:  "Mt. Lavaflow N (Lava Raised)",
	66:  "Mt. Lavaflow NE",
	67:  "Mt. Lavaflow (No Lava)",
	68:  "Mt. Lavaflow N (No Lava)",
	69:  "Mt. Lavaflow NW",
	70:  "Starship 1",
	71:  "Starship 2",
	72:  "Starship 3",
	73:  "Starship 5",
	74:  "Starship Idolcomp Room",
	75:  "Secret Island",
	76:  "Crashed Starship 1",
	77:  "Crashed Starship 2",
	78:  "Crashed Starship 3",
	79:  "Crashed Starship 5",
	80:  "Crashed Starship 6",
	81:  "Samurai Room",
	82:  "Hotel Room Left-2",
	83:  "Hotel Room Left-1",
	84:  "Fossil Center Side Room 1",
	85:  "Nighttime Harbor Area",
	86:  "BB Base 3F",
	87:  "BB Base 4F",
	88:  "BB Base 5F",
	89:  "Pirate Ship 2F Chest Room",
	90:  "Pirate Ship 3F Chest Room",
	91:  "Pirate Ship 2F Misc Room",
	92:  "Starship 4",
	93:  "Crashed Starship 4",
	94:  "Guhnash",
	95:  "Crash 1",
	96:  "Ocean",
	97:  "Fossil Center Warehouse (Pre-Final Battle)",
	98:  "Small Guhnash 1",
	99:  "Small Guhnash 2",
	100: "Crash 2",
	101: "Tunnel #1 Track",
	102: "Secret Tunnel 1",
	103: "Secret Tunnel 2",
	104: "Tunnel #5 Track",
	105: "Secret Tunnel 3",
	106: "Secret Tunnel 4",
	107: "Buggy Fossil Stadium 1",
	108: "Buggy Fossil Stadium 2",
	109: "Buggy Fossil Stadium 3",
	110: "Buggy Fossil Stadium 4",
	111: "Buggy Fossil Stadium 5",
	112: "Buggy Fossil Stadium 6",
	113: "Buggy Fossil Stadium 7",
	114: "Buggy Fossil Stadium 8",
	115: "Buggy Fossil Stadium 9",
	116: "Knotwood Forest",
	117: "Digadig Village",
	118: "Guild Area",
	119: "Fighter Area",
	120: "Park Area",
	121: "Trial Dig Site",
	122: "Fossil Center Warehouse (Time Machine)",
	123: "Buggy Fossil Stadium 10"
]
