let movementNames = [
	"n/a",
	"jump",
	"spin",
	"big spin",
	"fall front",
	"stand up from front",
	"fall through hole",
	"land from hole",
	"shake",
	"squish",
	"ascend",
	"descend",
	"jump and squish",
	"teleport",
	"shrink",
	"grow bigger",
	"lay front",
	"small",
	"sideways",
	"righten from sideways",
	"fall back",
	"lay back",
	"stand up from back",
	"fall down sideways",
]
