name: Build carbonizer

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    # - name: Run tests
    #   run: swift test -v
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.10.1-release
        tag: 5.10.1-RELEASE
    - name: Build
      run: swift build -Xswiftc -DIN_CI
